// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tUB_qf_1m5qYbgj_fzf7m3aQHtNDe7E',
    appId: '1:1070554179849:android:632538995846b1d56f4bd8',
    messagingSenderId: '1070554179849',
    projectId: 'imam-development-programme',
    storageBucket: 'imam-development-programme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNv_k5ixO-sgeSBxilocrC-wSaCNDBE0',
    appId: '1:1070554179849:ios:d301e501ac0a3fa16f4bd8',
    messagingSenderId: '1070554179849',
    projectId: 'imam-development-programme',
    storageBucket: 'imam-development-programme.appspot.com',
    androidClientId: '1070554179849-5cijot4asvubcnfkk8t047e7n3k9fv8s.apps.googleusercontent.com',
    iosClientId: '1070554179849-o3p3tpnpc4kafin8o2hrp2gaij3obarn.apps.googleusercontent.com',
    iosBundleId: 'com.tasnim.idp',
  );
}
